# Generated by Django 5.0.2 on 2024-03-01 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_save'),
        ('course', '0003_alter_course_students_alter_course_topics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked', models.BooleanField(default=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_StudentProgress', to='course.page')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentProgress', to='core.profile')),
            ],
            options={
                'unique_together': {('student', 'page')},
            },
        ),
    ]
