# Generated by Django 4.2.2 on 2023-11-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bitesizable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='bitesizable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='bitesizable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='bitesizable',
            field=models.BooleanField(default=False),
        ),
    ]
