# Generated by Django 4.2.7 on 2023-11-28 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_profiletag_delete_blogpost_delete_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.DeleteModel(
            name='ProfileTag',
        ),
    ]
